### ISSUE TITLE
Could the react-background-slider manage no animation when only one image is provided

### ISSUE THREAD

**Issue by moronyoh** [u2ix/react-background-slider#3]
Hello,
This is not really an issue, it's more a feature.
I'm using your react-background-slider in my website for displaying background images. But in some of my pages I only have one image. So my question is could this slider don not animate when only 1 image is provided ?

Yohan

**Comment by u2ix** [comment]
Hello Yohan

Thanks for submitting an issue.
In your case, I would highly suggest against loading the library in the case of only one image due to performance reasons. For the loading performance of your app, it would be best to just load this component if the slideshow is needed (there is more then one image).

You can use the lazy loading feature of the latest React 16.7.0 like follows:
```
import React, { Component, Suspense } from 'react';
const BackgroundSlider = React.lazy(() => import('react-background-slider'))

<div>
  { imgs.length > 1
    ? <Suspense fallback={null} >
        <BackgroundSlider images={imgs} duration={8} transition={2} />
      </Suspense>
    : <img src={imgs[0]} alt="background" className="background-img" />
  }
</div>
```

Don't forget to add appropriate CSS for the background image.
